services:
  - type: web
    name: financial_platform_springboot
    runtime: docker
    dockerfilePath: ./Dockerfile
    healthCheckPath: /health
    envVars:
      - key: SECRET_KEY
        sync: false
      - key: ALLOWED_ORIGINS
        sync: false
      - key: POSTGRES_URI
        sync: false
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
      - key: GOOGLE_GEMINI_API_KEY
        sync: false
      - key: GOOGLE_GEMINI_AI_MODEL
        sync: false
      - key: GROQ_API_KEY
        sync: false
      - key: GROQ_MODEL_NAME
        sync: false
      - key: RESEND_API_KEY
        sync: false
      - key: RESEND_MAILER_SENDER
        sync: false
